<?php

use Illuminate\Database\Seeder;

class MembersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('members')->delete();

        \DB::table('members')->insert(array(
            0 => array(
                'id' => 1,
                'status' => 'active',
                'firstname' => 'Sebastian',
                'lastname' => 'Fix',
                'email' => 'sebastian.fix@smartgate.ch',
                'mobile' => null,
                'github' => 'StanBarrows',
                'birthdate' => null,
                'member_since' => '2017-08-17 00:00:00',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ),
            1 => array(
                'id' => 2,
                'status' => 'active',
                'firstname' => 'Matthias',
                'lastname' => 'Cullmann',
                'email' => 'matthias.cullmann@baloise.ch',
                'mobile' => null,
                'github' => 'culmat',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ),
            2 => array(
                'id' => 3,
                'status' => 'active',
                'firstname' => 'Andres',
                'lastname' => 'Gartmann',
                'email' => 'andres.gartmann@gmx.ch',
                'mobile' => null,
                'github' => 'andgart',
                'birthdate' => null,
                'member_since' => '2017-06-16 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:20:15',
                'deleted_at' => null,
            ),
            3 => array(
                'id' => 4,
                'status' => 'active',
                'firstname' => 'Christoph',
                'lastname' => 'Schmid',
                'email' => 'Christoph-D.Schmid@swissonline.ch',
                'mobile' => null,
                'github' => 'schmidchr',
                'birthdate' => null,
                'member_since' => '2017-08-17 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:20:25',
                'deleted_at' => null,
            ),
            4 => array(
                'id' => 5,
                'status' => 'active',
                'firstname' => 'Dario',
                'lastname' => 'Todaro',
                'email' => 'dario.todaro@bluesky-it.ch',
                'mobile' => null,
                'github' => 'dariotodaro',
                'birthdate' => null,
                'member_since' => '2018-01-18 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:20:37',
                'deleted_at' => null,
            ),
            5 => array(
                'id' => 6,
                'status' => 'active',
                'firstname' => 'Dominik',
                'lastname' => 'Berger',
                'email' => 'dbe@bluesky-it.ch',
                'mobile' => null,
                'github' => null,
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:20:48',
                'deleted_at' => null,
            ),
            6 => array(
                'id' => 7,
                'status' => 'active',
                'firstname' => 'Jonas',
                'lastname' => 'Jatsch',
                'email' => 'jonas.jatsch@baloise.ch',
                'mobile' => null,
                'github' => 'JJatsch',
                'birthdate' => null,
                'member_since' => '2017-06-06 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:20:57',
                'deleted_at' => null,
            ),
            7 => array(
                'id' => 8,
                'status' => 'active',
                'firstname' => 'Jutta',
                'lastname' => 'Jerlich',
                'email' => 'jutta.jerlich@gmail.com',
                'mobile' => null,
                'github' => 'jjerlich',
                'birthdate' => null,
                'member_since' => '2017-07-06 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:09',
                'deleted_at' => null,
            ),
            8 => array(
                'id' => 9,
                'status' => 'active',
                'firstname' => 'Marina',
                'lastname' => 'Morawietz',
                'email' => 'marina.morawietz@fhnw.ch',
                'mobile' => null,
                'github' => 'mabrimo',
                'birthdate' => null,
                'member_since' => '2017-07-08 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:22:37',
                'deleted_at' => null,
            ),
            9 => array(
                'id' => 10,
                'status' => 'active',
                'firstname' => 'Martin',
                'lastname' => 'Christen',
                'email' => 'martin.christen@fhnw.ch',
                'mobile' => null,
                'github' => 'martinchristen',
                'birthdate' => null,
                'member_since' => '2017-06-16 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:22:45',
                'deleted_at' => null,
            ),
            10 => array(
                'id' => 11,
                'status' => 'active',
                'firstname' => 'Michael',
                'lastname' => 'Wyss',
                'email' => 'michael.wyss@bs.ch',
                'mobile' => null,
                'github' => 'michaelwyss',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:22:55',
                'deleted_at' => null,
            ),
            11 => array(
                'id' => 12,
                'status' => 'active',
                'firstname' => 'Michel',
                'lastname' => 'Pfirter',
                'email' => 'michel.pfirter@baloise.ch',
                'mobile' => null,
                'github' => 'michelpfirter',
                'birthdate' => null,
                'member_since' => '2017-08-11 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:23:03',
                'deleted_at' => null,
            ),
            12 => array(
                'id' => 13,
                'status' => 'active',
                'firstname' => 'Nely',
                'lastname' => 'Gaulea',
                'email' => 'nely.gaulea@mail.mcgill.ca',
                'mobile' => null,
                'github' => 'nelyy',
                'birthdate' => null,
                'member_since' => '2017-08-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:23:11',
                'deleted_at' => null,
            ),
            13 => array(
                'id' => 14,
                'status' => 'active',
                'firstname' => 'Oliver',
                'lastname' => 'Fritsch',
                'email' => 'oliver.fritsch@baloise.ch',
                'mobile' => null,
                'github' => 'OliverFritsch',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:23:17',
                'deleted_at' => null,
            ),
            14 => array(
                'id' => 15,
                'status' => 'active',
                'firstname' => 'Oliver',
                'lastname' => 'Reist',
                'email' => 'oliver.reist@smartgate.ch',
                'mobile' => null,
                'github' => 'genusshaus',
                'birthdate' => null,
                'member_since' => '2017-08-26 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:23:24',
                'deleted_at' => null,
            ),
            15 => array(
                'id' => 16,
                'status' => 'active',
                'firstname' => 'Pascal',
                'lastname' => 'Stucki',
                'email' => 'pascal.stucki@bs.ch',
                'mobile' => null,
                'github' => 'stupas',
                'birthdate' => null,
                'member_since' => '2017-10-18 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:22:07',
                'deleted_at' => null,
            ),
            16 => array(
                'id' => 17,
                'status' => 'active',
                'firstname' => 'Rolf',
                'lastname' => 'Schaub',
                'email' => 'rolf.schaub@ict-scouts.ch',
                'mobile' => null,
                'github' => 'rolf0408',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:59',
                'deleted_at' => null,
            ),
            17 => array(
                'id' => 18,
                'status' => 'active',
                'firstname' => 'Sabine',
                'lastname' => 'Schneeberger',
                'email' => 'sabine.schneeberger@bs.ch',
                'mobile' => null,
                'github' => 'sabinsc',
                'birthdate' => null,
                'member_since' => '2017-08-02 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:51',
                'deleted_at' => null,
            ),
            18 => array(
                'id' => 19,
                'status' => 'active',
                'firstname' => 'Stefani',
                'lastname' => 'Gerber',
                'email' => 'stefani.gerber@bluesky-it.ch',
                'mobile' => null,
                'github' => 'teddybeaker',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:44',
                'deleted_at' => null,
            ),
            19 => array(
                'id' => 20,
                'status' => 'active',
                'firstname' => 'Stephan',
                'lastname' => 'Jüngling',
                'email' => 'stephan.juengling@fhnw.ch',
                'mobile' => null,
                'github' => 'juengls',
                'birthdate' => null,
                'member_since' => '2017-08-02 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:34',
                'deleted_at' => null,
            ),
            20 => array(
                'id' => 21,
                'status' => 'active',
                'firstname' => 'Thomas',
                'lastname' => 'Brenzikofe',
                'email' => 'thomas.brenzikofer@baselarea.swiss',
                'mobile' => null,
                'github' => 'Brenzikofer',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:26',
                'deleted_at' => null,
            ),
            21 => array(
                'id' => 22,
                'status' => 'active',
                'firstname' => 'Vivienne',
                'lastname' => 'Mayer',
                'email' => 'vivienne.mayer@bs.ch',
                'mobile' => null,
                'github' => 'mayvi',
                'birthdate' => null,
                'member_since' => '2017-05-29 00:00:00',
                'created_at' => null,
                'updated_at' => '2018-05-03 13:21:18',
                'deleted_at' => null,
            ),
        ));
    }
}
