sudo: required
language: php
dist: trusty

php:
- 7.2

services:
- mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
  chrome: stable

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart

install:
- travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux &

- mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'

- cp .env.travis .env
- cp phpunit.travis.xml phpunit.xml

- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

- php artisan key:generate
- php artisan serve &

script:
- phpunit
- php artisan dusk

after_success:
  - chmod +x ./travis.success.sh; ./travis.success.sh