sudo: required

dist: trusty

language: php

php:
- 7.1

services:
- mysq

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  chrome: stable

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('testing') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ptesting
  - sudo service mysql restart

install:
- travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux &

- mysql -e 'create database testing;'

- cp .env.travis .env
- cp phpunit.travis.xml phpunit.xml

- php artisan key:generate
- php artisan serve &

script:
- phpunit

after_success:
  - chmod +x ./travis.success.sh; ./travis.success.sh